import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/(home)/header";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Joshua Rashtian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-50 dark:bg-zinc-800`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
